### ISSUE TITLE
Change translations to use XML String resources

### ISSUE THREAD

**Issue by robpvn** [PintaProject/PintaDemoExtension#2]
Depends on issue #1.

Currently translations are with Mono.Posix GetString, which is wrong both because we don't want to bundle translations with Pinta itself and because Mono.Posix isn't working on Windows right now. We want to do it like th e NIght vision add-in.

**Comment by cameronwhite** [comment]
Fixed with the changes in https://bugs.launchpad.net/pinta/+bug/992420
